USE [master]
GO
/****** Object:  Database [BeSarahaDB]    Script Date: 5/17/2023 8:41:45 AM ******/
CREATE DATABASE [BeSarahaDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BeSarahaDB', FILENAME = N'D:\SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BeSarahaDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BeSarahaDB_log', FILENAME = N'D:\SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BeSarahaDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [BeSarahaDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BeSarahaDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BeSarahaDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BeSarahaDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BeSarahaDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BeSarahaDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BeSarahaDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [BeSarahaDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BeSarahaDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BeSarahaDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BeSarahaDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BeSarahaDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BeSarahaDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BeSarahaDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BeSarahaDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BeSarahaDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BeSarahaDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [BeSarahaDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BeSarahaDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BeSarahaDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BeSarahaDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BeSarahaDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BeSarahaDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BeSarahaDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BeSarahaDB] SET RECOVERY FULL 
GO
ALTER DATABASE [BeSarahaDB] SET  MULTI_USER 
GO
ALTER DATABASE [BeSarahaDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BeSarahaDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BeSarahaDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BeSarahaDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BeSarahaDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BeSarahaDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'BeSarahaDB', N'ON'
GO
ALTER DATABASE [BeSarahaDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [BeSarahaDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [BeSarahaDB]
GO
/****** Object:  Table [dbo].[Messages]    Script Date: 5/17/2023 8:41:45 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Messages](
	[userid] [int] NOT NULL,
	[text] [nvarchar](500) NOT NULL,
	[date] [datetime] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 5/17/2023 8:41:45 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[email] [varchar](80) NOT NULL,
	[password] [nvarchar](300) NOT NULL,
	[firstname] [nvarchar](50) NOT NULL,
	[lastname] [nvarchar](50) NOT NULL,
	[picture] [varchar](150) NULL,
	[profileurl] [varchar](50) NOT NULL,
	[followersCount] [int] NOT NULL,
	[followingCount] [int] NOT NULL,
	[messagesCount] [int] NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [DF_Users_followersCount]  DEFAULT ((0)) FOR [followersCount]
GO
ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [DF_Users_followingCount]  DEFAULT ((0)) FOR [followingCount]
GO
ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [DF_Users_messagesCount]  DEFAULT ((0)) FOR [messagesCount]
GO
USE [master]
GO
ALTER DATABASE [BeSarahaDB] SET  READ_WRITE 
GO
